"""Keep Helm CRDs and RBAC aligned with the canonical raw manifests."""
import argparse
from pathlib import Path

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
expected = {root / 'charts/celld-operator/crds' / p.name: p.read_text()
            for p in (root / 'config/crd').glob('*.yaml')}
rbac = []
for document in (root / 'config/manager/operator.yaml').read_text().split('---'):
    if 'apiVersion: rbac.authorization.k8s.io/v1' not in document:
        continue
    document = document.strip().replace('name: celld-leader-election', 'name: {{ include "celld-operator.name" . }}-leader')
    document = document.replace('name: celld-operator', 'name: {{ include "celld-operator.name" . }}')
    document = document.replace('namespace: celld-system', 'namespace: {{ .Release.Namespace | quote }}')
    rbac.append(document)
expected[root / 'charts/celld-operator/templates/rbac.yaml'] = '# Generated by hack/sync-chart.py; edit config/manager/operator.yaml.\n' + '\n---\n'.join(rbac) + '\n'
fleet = []
for document in (root / 'config/rbac/fleet-namespace.yaml').read_text().split('---'):
    if 'apiVersion: rbac.authorization.k8s.io/v1' not in document:
        continue
    lines = [line for line in document.strip().splitlines() if not line.startswith('#')]
    document = '\n'.join(lines)
    document = document.replace('name: celld-fleet-operator', 'name: {{ include "celld-operator.name" $ }}-fleet')
    document = document.replace('    name: celld-operator\n    namespace: celld-system', '    name: {{ include "celld-operator.name" $ }}\n    namespace: {{ $.Release.Namespace | quote }}')
    document = document.replace('metadata:\n', 'metadata:\n  namespace: {{ . | quote }}\n', 1)
    fleet.append(document)
expected[root / 'charts/celld-operator/templates/rbac-fleet-namespaces.yaml'] = ('# Generated by hack/sync-chart.py; edit config/rbac/fleet-namespace.yaml.\n'
    '{{- range .Values.fleetNamespaces }}\n---\n' + '\n---\n'.join(fleet) + '\n{{- end }}\n')
for path, value in expected.items():
    if args.check:
        if not path.exists() or path.read_text() != value:
            raise SystemExit(f'Chart drift: {path.relative_to(root)}; run make chart-sync')
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(value)
if args.check:
    print('Chart CRDs and RBAC match canonical manifests.')
