//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationNodeStatus) DeepCopyInto(out *ApplicationNodeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationNodeStatus.
func (in *ApplicationNodeStatus) DeepCopy() *ApplicationNodeStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationStatus) DeepCopyInto(out *ApplicationStatus) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	if in.ObservedVersion != nil {
		in, out := &in.ObservedVersion, &out.ObservedVersion
		*out = new(ApplicationVersion)
		**out = **in
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]ApplicationVersionCount, len(*in))
		copy(*out, *in)
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]ApplicationNodeStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationStatus.
func (in *ApplicationStatus) DeepCopy() *ApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationVersion) DeepCopyInto(out *ApplicationVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationVersion.
func (in *ApplicationVersion) DeepCopy() *ApplicationVersion {
	if in == nil {
		return nil
	}
	out := new(ApplicationVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationVersionCount) DeepCopyInto(out *ApplicationVersionCount) {
	*out = *in
	out.ApplicationVersion = in.ApplicationVersion
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationVersionCount.
func (in *ApplicationVersionCount) DeepCopy() *ApplicationVersionCount {
	if in == nil {
		return nil
	}
	out := new(ApplicationVersionCount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPolicy) DeepCopyInto(out *CapacityPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPolicy.
func (in *CapacityPolicy) DeepCopy() *CapacityPolicy {
	if in == nil {
		return nil
	}
	out := new(CapacityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityStatus) DeepCopyInto(out *CapacityStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityStatus.
func (in *CapacityStatus) DeepCopy() *CapacityStatus {
	if in == nil {
		return nil
	}
	out := new(CapacityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldFleet) DeepCopyInto(out *CelldFleet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldFleet.
func (in *CelldFleet) DeepCopy() *CelldFleet {
	if in == nil {
		return nil
	}
	out := new(CelldFleet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CelldFleet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldFleetList) DeepCopyInto(out *CelldFleetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CelldFleet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldFleetList.
func (in *CelldFleetList) DeepCopy() *CelldFleetList {
	if in == nil {
		return nil
	}
	out := new(CelldFleetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CelldFleetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldFleetSpec) DeepCopyInto(out *CelldFleetSpec) {
	*out = *in
	if in.Maintenance != nil {
		in, out := &in.Maintenance, &out.Maintenance
		*out = new(MaintenanceSpec)
		**out = **in
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(CapacityPolicy)
		**out = **in
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.Placement.DeepCopyInto(&out.Placement)
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = new(ExecutionSpec)
		**out = **in
	}
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(LifecycleSpec)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]FleetEnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetrySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Routing != nil {
		in, out := &in.Routing, &out.Routing
		*out = new(RoutingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldFleetSpec.
func (in *CelldFleetSpec) DeepCopy() *CelldFleetSpec {
	if in == nil {
		return nil
	}
	out := new(CelldFleetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldFleetStatus) DeepCopyInto(out *CelldFleetStatus) {
	*out = *in
	if in.Application != nil {
		in, out := &in.Application, &out.Application
		*out = new(ApplicationStatus)
		(*in).DeepCopyInto(*out)
	}
	out.Capacity = in.Capacity
	out.Lifecycle = in.Lifecycle
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldFleetStatus.
func (in *CelldFleetStatus) DeepCopy() *CelldFleetStatus {
	if in == nil {
		return nil
	}
	out := new(CelldFleetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldPreview) DeepCopyInto(out *CelldPreview) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldPreview.
func (in *CelldPreview) DeepCopy() *CelldPreview {
	if in == nil {
		return nil
	}
	out := new(CelldPreview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CelldPreview) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldPreviewList) DeepCopyInto(out *CelldPreviewList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CelldPreview, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldPreviewList.
func (in *CelldPreviewList) DeepCopy() *CelldPreviewList {
	if in == nil {
		return nil
	}
	out := new(CelldPreviewList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CelldPreviewList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldPreviewPool) DeepCopyInto(out *CelldPreviewPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldPreviewPool.
func (in *CelldPreviewPool) DeepCopy() *CelldPreviewPool {
	if in == nil {
		return nil
	}
	out := new(CelldPreviewPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CelldPreviewPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldPreviewPoolList) DeepCopyInto(out *CelldPreviewPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CelldPreviewPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldPreviewPoolList.
func (in *CelldPreviewPoolList) DeepCopy() *CelldPreviewPoolList {
	if in == nil {
		return nil
	}
	out := new(CelldPreviewPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CelldPreviewPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldPreviewPoolSpec) DeepCopyInto(out *CelldPreviewPoolSpec) {
	*out = *in
	if in.Seeding != nil {
		in, out := &in.Seeding, &out.Seeding
		*out = new(PreviewSeedingSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.Routing.DeepCopyInto(&out.Routing)
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = new(ExecutionSpec)
		**out = **in
	}
	if in.Scratch != nil {
		in, out := &in.Scratch, &out.Scratch
		*out = new(ScratchSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldPreviewPoolSpec.
func (in *CelldPreviewPoolSpec) DeepCopy() *CelldPreviewPoolSpec {
	if in == nil {
		return nil
	}
	out := new(CelldPreviewPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldPreviewSeed) DeepCopyInto(out *CelldPreviewSeed) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldPreviewSeed.
func (in *CelldPreviewSeed) DeepCopy() *CelldPreviewSeed {
	if in == nil {
		return nil
	}
	out := new(CelldPreviewSeed)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CelldPreviewSeed) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldPreviewSeedList) DeepCopyInto(out *CelldPreviewSeedList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CelldPreviewSeed, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldPreviewSeedList.
func (in *CelldPreviewSeedList) DeepCopy() *CelldPreviewSeedList {
	if in == nil {
		return nil
	}
	out := new(CelldPreviewSeedList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CelldPreviewSeedList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldPreviewSeedSpec) DeepCopyInto(out *CelldPreviewSeedSpec) {
	*out = *in
	in.Request.DeepCopyInto(&out.Request)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldPreviewSeedSpec.
func (in *CelldPreviewSeedSpec) DeepCopy() *CelldPreviewSeedSpec {
	if in == nil {
		return nil
	}
	out := new(CelldPreviewSeedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldPreviewSeedStatus) DeepCopyInto(out *CelldPreviewSeedStatus) {
	*out = *in
	if in.Manifest != nil {
		in, out := &in.Manifest, &out.Manifest
		*out = new(PreviewSnapshotManifest)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldPreviewSeedStatus.
func (in *CelldPreviewSeedStatus) DeepCopy() *CelldPreviewSeedStatus {
	if in == nil {
		return nil
	}
	out := new(CelldPreviewSeedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldPreviewSpec) DeepCopyInto(out *CelldPreviewSpec) {
	*out = *in
	if in.Seed != nil {
		in, out := &in.Seed, &out.Seed
		*out = new(PreviewSeedSpec)
		(*in).DeepCopyInto(*out)
	}
	out.PoolRef = in.PoolRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldPreviewSpec.
func (in *CelldPreviewSpec) DeepCopy() *CelldPreviewSpec {
	if in == nil {
		return nil
	}
	out := new(CelldPreviewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldPreviewStatus) DeepCopyInto(out *CelldPreviewStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldPreviewStatus.
func (in *CelldPreviewStatus) DeepCopy() *CelldPreviewStatus {
	if in == nil {
		return nil
	}
	out := new(CelldPreviewStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldStorageReservation) DeepCopyInto(out *CelldStorageReservation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldStorageReservation.
func (in *CelldStorageReservation) DeepCopy() *CelldStorageReservation {
	if in == nil {
		return nil
	}
	out := new(CelldStorageReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CelldStorageReservation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelldStorageReservationList) DeepCopyInto(out *CelldStorageReservationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CelldStorageReservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelldStorageReservationList.
func (in *CelldStorageReservationList) DeepCopy() *CelldStorageReservationList {
	if in == nil {
		return nil
	}
	out := new(CelldStorageReservationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CelldStorageReservationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorEgress) DeepCopyInto(out *CollectorEgress) {
	*out = *in
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorEgress.
func (in *CollectorEgress) DeepCopy() *CollectorEgress {
	if in == nil {
		return nil
	}
	out := new(CollectorEgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionSpec) DeepCopyInto(out *ExecutionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionSpec.
func (in *ExecutionSpec) DeepCopy() *ExecutionSpec {
	if in == nil {
		return nil
	}
	out := new(ExecutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetEnvVar) DeepCopyInto(out *FleetEnvVar) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetEnvVar.
func (in *FleetEnvVar) DeepCopy() *FleetEnvVar {
	if in == nil {
		return nil
	}
	out := new(FleetEnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayRouting) DeepCopyInto(out *GatewayRouting) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayRouting.
func (in *GatewayRouting) DeepCopy() *GatewayRouting {
	if in == nil {
		return nil
	}
	out := new(GatewayRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressRouting) DeepCopyInto(out *IngressRouting) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressRouting.
func (in *IngressRouting) DeepCopy() *IngressRouting {
	if in == nil {
		return nil
	}
	out := new(IngressRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleSpec) DeepCopyInto(out *LifecycleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleSpec.
func (in *LifecycleSpec) DeepCopy() *LifecycleSpec {
	if in == nil {
		return nil
	}
	out := new(LifecycleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleStatus) DeepCopyInto(out *LifecycleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleStatus.
func (in *LifecycleStatus) DeepCopy() *LifecycleStatus {
	if in == nil {
		return nil
	}
	out := new(LifecycleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceSpec) DeepCopyInto(out *MaintenanceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceSpec.
func (in *MaintenanceSpec) DeepCopy() *MaintenanceSpec {
	if in == nil {
		return nil
	}
	out := new(MaintenanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStoreEndpoint) DeepCopyInto(out *ObjectStoreEndpoint) {
	*out = *in
	in.Egress.DeepCopyInto(&out.Egress)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStoreEndpoint.
func (in *ObjectStoreEndpoint) DeepCopy() *ObjectStoreEndpoint {
	if in == nil {
		return nil
	}
	out := new(ObjectStoreEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementSpec) DeepCopyInto(out *PlacementSpec) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementSpec.
func (in *PlacementSpec) DeepCopy() *PlacementSpec {
	if in == nil {
		return nil
	}
	out := new(PlacementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewObjectReference) DeepCopyInto(out *PreviewObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewObjectReference.
func (in *PreviewObjectReference) DeepCopy() *PreviewObjectReference {
	if in == nil {
		return nil
	}
	out := new(PreviewObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewObjectSnapshot) DeepCopyInto(out *PreviewObjectSnapshot) {
	*out = *in
	out.PreviewObjectReference = in.PreviewObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewObjectSnapshot.
func (in *PreviewObjectSnapshot) DeepCopy() *PreviewObjectSnapshot {
	if in == nil {
		return nil
	}
	out := new(PreviewObjectSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewPoolReference) DeepCopyInto(out *PreviewPoolReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewPoolReference.
func (in *PreviewPoolReference) DeepCopy() *PreviewPoolReference {
	if in == nil {
		return nil
	}
	out := new(PreviewPoolReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewPoolStorage) DeepCopyInto(out *PreviewPoolStorage) {
	*out = *in
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(ObjectStoreEndpoint)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewPoolStorage.
func (in *PreviewPoolStorage) DeepCopy() *PreviewPoolStorage {
	if in == nil {
		return nil
	}
	out := new(PreviewPoolStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewRouting) DeepCopyInto(out *PreviewRouting) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewayRouting)
		**out = **in
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressRouting)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewRouting.
func (in *PreviewRouting) DeepCopy() *PreviewRouting {
	if in == nil {
		return nil
	}
	out := new(PreviewRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewSeedRequest) DeepCopyInto(out *PreviewSeedRequest) {
	*out = *in
	out.SourceFleet = in.SourceFleet
	out.Target = in.Target
	in.Selection.DeepCopyInto(&out.Selection)
	in.Deadline.DeepCopyInto(&out.Deadline)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewSeedRequest.
func (in *PreviewSeedRequest) DeepCopy() *PreviewSeedRequest {
	if in == nil {
		return nil
	}
	out := new(PreviewSeedRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewSeedSource) DeepCopyInto(out *PreviewSeedSource) {
	*out = *in
	out.FleetRef = in.FleetRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewSeedSource.
func (in *PreviewSeedSource) DeepCopy() *PreviewSeedSource {
	if in == nil {
		return nil
	}
	out := new(PreviewSeedSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewSeedSpec) DeepCopyInto(out *PreviewSeedSpec) {
	*out = *in
	if in.Objects != nil {
		in, out := &in.Objects, &out.Objects
		*out = make([]PreviewObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewSeedSpec.
func (in *PreviewSeedSpec) DeepCopy() *PreviewSeedSpec {
	if in == nil {
		return nil
	}
	out := new(PreviewSeedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewSeedTarget) DeepCopyInto(out *PreviewSeedTarget) {
	*out = *in
	out.PoolRef = in.PoolRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewSeedTarget.
func (in *PreviewSeedTarget) DeepCopy() *PreviewSeedTarget {
	if in == nil {
		return nil
	}
	out := new(PreviewSeedTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewSeedingSpec) DeepCopyInto(out *PreviewSeedingSpec) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]PreviewSeedSource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewSeedingSpec.
func (in *PreviewSeedingSpec) DeepCopy() *PreviewSeedingSpec {
	if in == nil {
		return nil
	}
	out := new(PreviewSeedingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewSnapshotManifest) DeepCopyInto(out *PreviewSnapshotManifest) {
	*out = *in
	if in.Objects != nil {
		in, out := &in.Objects, &out.Objects
		*out = make([]PreviewObjectSnapshot, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewSnapshotManifest.
func (in *PreviewSnapshotManifest) DeepCopy() *PreviewSnapshotManifest {
	if in == nil {
		return nil
	}
	out := new(PreviewSnapshotManifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationSpec) DeepCopyInto(out *ReservationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationSpec.
func (in *ReservationSpec) DeepCopy() *ReservationSpec {
	if in == nil {
		return nil
	}
	out := new(ReservationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingSource) DeepCopyInto(out *RoutingSource) {
	*out = *in
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingSource.
func (in *RoutingSource) DeepCopy() *RoutingSource {
	if in == nil {
		return nil
	}
	out := new(RoutingSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingSpec) DeepCopyInto(out *RoutingSpec) {
	*out = *in
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]RouteHostname, len(*in))
		copy(*out, *in)
	}
	in.Source.DeepCopyInto(&out.Source)
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewayRouting)
		**out = **in
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressRouting)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingSpec.
func (in *RoutingSpec) DeepCopy() *RoutingSpec {
	if in == nil {
		return nil
	}
	out := new(RoutingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScratchSpec) DeepCopyInto(out *ScratchSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScratchSpec.
func (in *ScratchSpec) DeepCopy() *ScratchSpec {
	if in == nil {
		return nil
	}
	out := new(ScratchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeedFleetReference) DeepCopyInto(out *SeedFleetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeedFleetReference.
func (in *SeedFleetReference) DeepCopy() *SeedFleetReference {
	if in == nil {
		return nil
	}
	out := new(SeedFleetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeedReference) DeepCopyInto(out *SeedReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeedReference.
func (in *SeedReference) DeepCopy() *SeedReference {
	if in == nil {
		return nil
	}
	out := new(SeedReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolReference) DeepCopyInto(out *StoragePoolReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolReference.
func (in *StoragePoolReference) DeepCopy() *StoragePoolReference {
	if in == nil {
		return nil
	}
	out := new(StoragePoolReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.Initialization != nil {
		in, out := &in.Initialization, &out.Initialization
		*out = new(SeedReference)
		**out = **in
	}
	if in.PoolRef != nil {
		in, out := &in.PoolRef, &out.PoolRef
		*out = new(StoragePoolReference)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(ObjectStoreEndpoint)
		(*in).DeepCopyInto(*out)
	}
	if in.Scratch != nil {
		in, out := &in.Scratch, &out.Scratch
		*out = new(ScratchSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetrySecretKeyRef) DeepCopyInto(out *TelemetrySecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetrySecretKeyRef.
func (in *TelemetrySecretKeyRef) DeepCopy() *TelemetrySecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(TelemetrySecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetrySpec) DeepCopyInto(out *TelemetrySpec) {
	*out = *in
	in.Egress.DeepCopyInto(&out.Egress)
	if in.HeadersSecretKeyRef != nil {
		in, out := &in.HeadersSecretKeyRef, &out.HeadersSecretKeyRef
		*out = new(TelemetrySecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetrySpec.
func (in *TelemetrySpec) DeepCopy() *TelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(TelemetrySpec)
	in.DeepCopyInto(out)
	return out
}
