{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "celld-operator.name" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: celld-operator
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
{{- end }}
