apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "celld-operator.name" . }}
  labels:
    {{- include "celld-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
