apiVersion: v2
name: celld-operator
description: Kubernetes lifecycle operator for celld on EKS, S3 and EBS
type: application
version: 0.1.0-dev
appVersion: dev
kubeVersion: '>=1.31.0-0'
annotations:
  licenses: Apache-2.0
